language:       generic
sudo:           required
dist:           xenial
git:
  submodules:   false

before_install: 
  - sudo apt-get update -qq
install:
  - sudo add-apt-repository -y ppa:avsm
  - sudo apt-get update
  - sudo apt-get install -y ocaml opam aspcud time libgtk2.0-dev libgtksourceview2.0-dev emacs
  - opam init --yes --no-setup
  - eval $(opam config env)
  - opam install lablgtk camlp5 num --yes --verbose
script:
  - make 

